apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-batch
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kube-batch
  template:
    metadata:
      labels:
        app: kube-batch
    spec:
      volumes:
        - name: scheduler-conf
          configMap:
            name: scheduler-conf
            items:
              - key: scheduler-conf.yaml
                path: scheduler-conf.yaml
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}/kube-batch:{{ .Values.image.tag }}"
        args: ["--logtostderr", "--v", "4", "--scheduler-conf", "/etc/scheduler-conf/scheduler-conf.yaml"]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
          - name: scheduler-conf
            readOnly: true
            mountPath: "/etc/scheduler-conf"
